# Generated by Django 3.2.12 on 2023-09-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coder_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('designation', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=66)),
                ('yoe', models.IntegerField()),
                ('slug', models.SlugField(max_length=88, unique=True)),
            ],
            options={
                'ordering': ['-yoe'],
            },
        ),
        migrations.DeleteModel(
            name='codermodel',
        ),
    ]
