# Generated by Django 3.2.12 on 2023-09-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0002_auto_20230915_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coder_model',
            name='slug',
        ),
    ]
