# Generated by Django 3.2.12 on 2023-09-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0003_remove_coder_model_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coder_Model',
        ),
    ]
